### ISSUE TITLE
[Bug]: Using dashes in door, lift, or level names leads to an exception in the plugins

### ISSUE THREAD

**Issue by mxgrey** [open-rmf/rmf_simulation#109]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

2.2.1

### ROS distribution

Humble

### ROS installation type

Source build

### Description of the bug

I've found that if a floor, door, or lift name contains a dash, then gz classic plugins throw an exception during loading and then impacted infrastructure doesn't work.

I assume the infrastructure name is being put into something like a topic name that has some kind of character restrictions that we're not enforcing from the traffic editor. It's not great for the simulations to inexplicably fail due to choice of names, so maybe we should convert automatically dashes to underscores when they get used in places with character restrictions.

### Steps to reproduce the bug

Make a map in the traffic editor where a floor, door, or lift name contains a dash. Launch that map in simulation and stare in bewilderment when the door or lift doesn't move.

**Comment by luca-della-vedova** [comment]
I believe the exception is generated in [this line](https://github.com/open-rmf/rmf_simulation/blob/4bc0797080826befc5f8e49662151499a73ebe14/rmf_building_sim_gz_classic_plugins/src/door.cpp#L36), I tried in `gz` and it also fails but prints out the exception:

```
[ign-17] terminate called after throwing an instance of 'rclcpp::exceptions::InvalidNodeNameError'
[ign-17]   what():  Invalid node name: node name must not contain characters other than alphanumerics or '_':
[ign-17]   'plugin_main-door'
```

I'll open a PR with the proposed fix (validating the node name and substituting / removing where necessary, I suppose spaces and special characters are also technically allowed in `traffic-editor` but would definitely cause issues). There will be an extreme corner case of failures if people try to rely on (for example) `door-1` and `door_1` being two different entities but that is really quite a corner case that doesn't work now anyways.
