### ISSUE TITLE
[Bug]: Error in the slotcar.cpp when building from source on ROS2 humble rmf_robot_sim_gz_classic_plugins

### ISSUE THREAD

**Issue by RobLevv** [open-rmf/rmf_simulation#121]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 22.04

### Open-RMF installation type

Source build

### Open-RMF version or commit hash

f71d2d3d2fcc50e10537b995fc91f256668360da

### ROS distribution

Humble

### ROS installation type

Binaries

### Description of the bug

Error in the slotcar.cpp when building from source on ROS2 humble rmf_plugins_utils does not contain sanitize_node_name

```shell
/rmf_ws/src/rmf/rmf_simulation/rmf_robot_sim_gz_classic_plugins/src/slotcar.cpp:86:22: error: no type named 'sanitize_node_name' in namespace 'rmf_plugins_utils'
  rmf_plugins_utils::sanitize_node_name(node_name);
  ~~~~~~~~~~~~~~~~~~~^
1 error generated.
gmake[2]: *** [CMakeFiles/slotcar.dir/build.make:76: CMakeFiles/slotcar.dir/src/slotcar.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:221: CMakeFiles/slotcar.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

### Steps to reproduce the bug

1. download ROS2 humble binaries
2. Build from source  with the [instruction here](https://github.com/open-rmf/rmf?tab=readme-ov-file#building-from-source)

**Comment by luca-della-vedova** [comment]
Hello!

Are you sure you don't have any Open-RMF binaries installed? I can see how that would happen if you were to mix binaries and source build at the same time.
What happens if you run `sudo apt purge ros-<distro>-rmf* && sudo apt autoremove` as in the instructions you sent? Does any package get removed?

**Comment by RobLevv** [comment]
Thank yo for your answer,

Surprinsingly I had already run ```sudo apt purge ros-<distro>-rmf* && sudo apt autoremove``` but some binaries still remained, after running it again cleaning old build and rebuilding it seems to work fine

Thank you very much
