### ISSUE TITLE
[Bug]: Regression on ROS buildfarm for Rolling

### ISSUE THREAD

**Issue by Yadunund** [open-rmf/rmf_simulation#137]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### OS and version

Ubuntu 24.04

### Open-RMF installation type

Binaries

### Open-RMF version or commit hash

2.4.0

### ROS distribution

Rolling

### ROS installation type

Binaries

### Description of the bug

RBin jobs are failing https://build.ros2.org/view/Rbin_uN64/job/Rbin_uN64__rmf_building_sim_gz_plugins__ubuntu_noble_amd64__binary/68/

### Steps to reproduce the bug

https://build.ros2.org/view/Rbin_uN64/job/Rbin_uN64__rmf_building_sim_gz_plugins__ubuntu_noble_amd64__binary/68/

**Comment by luca-della-vedova** [comment]
This is caused by the ionic release and already fixed on main, just need a minor bump and re-release on rolling, I am part of the release org and will give a look at what the process is like
