### ISSUE TITLE
Make busy lift terminal output less threatening

### ISSUE THREAD

**Issue by mxgrey** [open-rmf/rmf_simulation#17]
A followup from this discussion: https://github.com/open-rmf/rmf/discussions/40#discussioncomment-677772

It would be nice if the message that gets outputted by the lift when it's busy carrying out a task could be reworked so that it doesn't lead users to think that something is wrong. We could reword it, or we could remove it altogether when the incoming requests perfectly matches the current request.

We could also consider revising the lift supervisor so that it doesn't duplicate this request message.

**Comment by arjo129** [comment]
Would it be sufficient to simply lower the log levels to debug rather than keep track of requests. At the same time, we could tweak the lift supervisor as you suggested.

**Comment by luca-della-vedova** [comment]
#89 should address this
