### ISSUE TITLE
Robot spinning unnecessarily

### ISSUE THREAD

**Issue by xiyuoh** [open-rmf/rmf_simulation#65]
### Description of the bug
Recent changes introduced a bug in simulation, where cleaning robots tend to spin on the spot in the middle of a cleaning task. In earlier commits, the robot only pauses at the spot instead of turning around. This can be reproduced in hotel world by running the `clean_lobby` task. The latest working commit without spinning is 80b22b90f3260d39865aef32efef0d0eecffc39e.

Edit: Observed when using demo fleet adapter, not `full_control`

No spinning:

https://user-images.githubusercontent.com/30265743/148749089-bf0af726-a23d-4e9c-98a4-be068241c25a.mp4

Spinning:

https://user-images.githubusercontent.com/30265743/148749108-ba8a8a80-341b-4e92-b089-ba0fa44de229.mp4

**Comment by Yadunund** [comment]
The behavior is not unique to cleaning and is observed for both `reversible` and `non-reversible` slotcars while following a path.

**Comment by luca-della-vedova** [comment]
> Recent changes introduced a bug in simulation, where cleaning robots tend to spin on the spot in the middle of a cleaning task. In earlier commits, the robot only pauses at the spot instead of turning around. This can be reproduced in hotel world by running the `clean_lobby` task. The latest working commit without spinning is [80b22b9](https://github.com/open-rmf/rmf_simulation/commit/80b22b90f3260d39865aef32efef0d0eecffc39e).

When you say that's the latest commit it means you tried all the different commits and the first one where the behavior is exhibited is the one that was merged immediately after the one you mentioned - https://github.com/open-rmf/rmf_simulation/pull/38?
If that's the case it sounds a bit strange, int https://github.com/open-rmf/rmf_simulation/pull/38 the only functional change is adding a check for reversibility [here](https://github.com/open-rmf/rmf_simulation/pull/38/files#diff-f16626539eec1bdb429fdfa326fba164536f1e53e572e6d58409340a7f114965R842) so the behavior for reversible robots shouldn't have changed

**Comment by xiyuoh** [comment]
Hmm I tried every commit from 0455e7aeece9e5eabecc8f0c4e00b8dd8c648d7d to 80b22b90f3260d39865aef32efef0d0eecffc39e and found that the one after (open-rmf/rmf_simulation#38) starts to exhibit the spinning behaviour.

**Comment by luca-della-vedova** [comment]
I tried to run the latest `main` in rmf_demos with the incriminated commit and this is what I see:

https://user-images.githubusercontent.com/9111558/148943569-4f29e71a-8acc-4c1a-9b55-bb93d8a8be0e.mp4

So there is one extra turn but I can't reproduce the long oscillating behavior, can you try a fresh `vcs pull`, clean build and post the output of `vcs status`?

**Comment by xiyuoh** [comment]
I believe the extra turn is normal before docking. Anyway my bad, i should have mentioned that this occurs when using the new demo fleet adapter for me, not sure what is causing the difference between the `rmf_simulation` commits. When i try it with the current `rmf_demos/main` and it works fine just like yours.

**Comment by luca-della-vedova** [comment]
I can reproduce, although only on Gazebo on my machine (i.e. doing `rmf_demos_ign` instead of `rmf_demos_gz` gets rid of the issue). Can you confirm that's the case for you as well?

**Comment by xiyuoh** [comment]
Yup same, the spinning doesn't occur in ignition for me too. I found that during the spinning, cleanerBotA is hovering between `rotate_towards_next_target` and `!rotate_towards_next_target`. Increasing the [close_enough threshold](https://github.com/open-rmf/rmf_simulation/blob/main/rmf_robot_sim_common/src/slotcar_common.cpp#L564) to 0.04 gets rid of the spinning in the docking cases, but i'm not sure that's a good fix

**Comment by luca-della-vedova** [comment]
> Yup same, the spinning doesn't occur in ignition for me too. I found that during the spinning, cleanerBotA is hovering between `rotate_towards_next_target` and `!rotate_towards_next_target`. Increasing the [close_enough threshold](https://github.com/open-rmf/rmf_simulation/blob/main/rmf_robot_sim_common/src/slotcar_common.cpp#L564) to 0.04 gets rid of the spinning in the docking cases, but i'm not sure that's a good fix

That would explain why there is a difference between the two simulators, in Gazebo we simulate the vehicle dynamics more accurately (i.e. we apply torques to the wheels and as a consequence robots move). In Ignition instead we do a much simpler kinematic simulation where we treat the vehicle as a box and set its target speed so I would expect minor differences in the behavior.
Imho 0.04 (4cm) is a very reasonable threshold, I'm happy to increase it to that value if it helps with this issue.

**Comment by xiyuoh** [comment]
I see! I ran all the demo cleaning tasks + a few other loops with the increased threshold, looks fine so far. If you are ok let's increase it, thanks!

**Comment by xiyuoh** [comment]
Closing this issue as the pause and spinning can be fixed altogether from the fleet adapter
