### ISSUE TITLE
Toggle floor in ignition sim

### ISSUE THREAD

**Issue by youliangtan** [open-rmf/rmf_simulation#66]
Since now the default `rmf_demos` world is a multi-floor hotel.world, we certainly need a similar floor toggle button on ignition gui. This floor toggle feature will be similar to what is currently available on  `_gz` gui.

**Comment by mayman99** [comment]
Hey, is someone working on this at the moment? I would like to give it a go.

**Comment by chianfern** [comment]
Yup, i'm looking at it currently, happy to discuss if needed!
