### ISSUE TITLE
Doors not working in latest Gazebo Fortress binary update

### ISSUE THREAD

**Issue by luca-della-vedova** [open-rmf/rmf_simulation#75]
### Required information:

- Operating system and version:
  - Any Ubuntu with binary fortress avaialble
- OpenRMF installation type:
  - From source
- Package or library, if applicable:
  - rmf_building_sim_common

### Description of the bug
Update of Gazebo Fortress from 6.9 to 6.10 changed the behavior of the `sdf::ElementPtr` that is passed to the `Configure` function, it now uses `sdf::Plugin` and no longer has access to the parent element.
This breaks our current behavior where, in both Gazebo classic and Gazebo, we use the element pointer to traverse up from the plugin to the door that contains it to read joint limits and apply smooth accelerations / decelerations.
Reference issue on the [gz-sim repo](https://github.com/gazebosim/gz-sim/issues/1561)

### Steps to reproduce the bug

1. Launch RMF using `ros2 launch rmf_demos_ign office_demo.launch`
2. Send a robot through a door
3. Door will not open

There will also be a printout about being unable to access the parent element when configuring the door plugin.

### Possible fixes
The issue can be fixed at the gz-sim level but that sounds like a non ideal approach since, although the behavior change was unintended, it is not a common use case and might be deprecated and removed in future versions.
A future-proof approach would involve using the ECM to access the joint properties, instead of traversing the SDF Element, as suggested in the linked issue.

**Comment by youliangtan** [comment]
Able to reproduce this error when running it with the [docker image](https://github.com/orgs/open-rmf/packages/container/package/rmf_deployment_template%2Frmf-simulation), with latest humble. Getting this error:
```
[ign-14] [ERROR] [1660148666.807621056] [plugin_hardware_door]: Unable to access parent sdf to retrieve joint limits
```
