### ISSUE TITLE
Error: no matching function for call to 'Get'

### ISSUE THREAD

**Issue by TheConstructAi** [open-rmf/rmf_simulation#85]
## Bug report
Following the steps for compilation for the main branch, humble release, gives this error:

Finished <<< rmf_traffic_editor_test_maps [2min 23s]
--- stderr: rmf_building_sim_gz_classic_plugins
/home/user/rmf_ws/src/rmf/rmf_simulation/rmf_building_sim_gz_classic_plugins/src/door.cpp:36:22: error: no matching function for call to 'Get'
    auto _ros_node = gazebo_ros::Node::Get(sdf, node_name);

Seems that the gazebo classic elements are not compatible with the ones installed for gazebo 11.

**Comment by TheConstructAi** [comment]
Solved it by replacing the code:
`
_readonly_common->init(gazebo_ros::Node::Get(sdf, node_name));`

By:

`  _readonly_common->init(gazebo_ros::Node::Get(sdf));`

**Comment by luca-della-vedova** [comment]
The change was introduced [here](https://github.com/open-rmf/rmf_simulation/pull/77) as part of Humble compatibility.

Can I check with you what's your ROS version, and the version of `ros-<distro>-gazebo-ros`?

**Comment by TheConstructAi** [comment]
Hi,

My version is Humble
user:~/ros2_ws/src$ ros2 pkg xml gazebo_ros | grep version
  <version>3.6.0</version>

Just run it again in a fully Ubuntu 22, Humble stock system an dsam issue. I'll try to push this fix to our fork and do a push request,

**Comment by Th3G4mbl3r** [comment]
i am having the same issue. for me Ubuntu 20.04, ROS2 version is galactic. And the gazebo_ros package version is 3.5.2. And i am following the build from source instructions as listed here except for distro i am using galactic. When i try to do it with Humble, i get a different set of errors but i am suspecting that may be due to the fact that i am still on Ubuntu 20.04 and not 22 yet.

**Comment by Th3G4mbl3r** [comment]
Has the galactic branch been released? i saw in the migration thread a comment saying that the galactic branch has not yet been released.

**Comment by Yadunund** [comment]
As mentioned above, `main` only supports `humble`. There is a `galactic-devel` branch you can checkout for source builds with galactic. You should keep in mind that ROS 2 Galactic will be [EOL](https://docs.ros.org/en/galactic/Releases.html) by end of November so we do not plan to support any galactic releases.

**Comment by luca-della-vedova** [comment]
This is fairly outdated (we now moved all the way to 24.04 and Jazzy), will close
